import { useState } from "react";
import Layout from "../components/Layout";

export default function Payments() {
  const [activeTab, setActiveTab] = useState("history");
  const [payoneerEmail, setPayoneerEmail] = useState("");
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
  };

  const stats = [
    { label: "Next Payout", value: "$0.00", icon: <svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>, color: "text-blue-600", bg: "bg-blue-50", border: "border-blue-100" },
    { label: "Total Paid", value: "$0.00", icon: <svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>, color: "text-emerald-600", bg: "bg-emerald-50", border: "border-emerald-100" },
    { label: "Paid Invoices", value: "0", icon: <svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>, color: "text-violet-600", bg: "bg-violet-50", border: "border-violet-100" },
    { label: "Rejected", value: "0", icon: <svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}><path strokeLinecap="round" strokeLinejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>, color: "text-red-500", bg: "bg-red-50", border: "border-red-100" },
  ];

  const paymentTerms = [
    { title: "1. Transaction Approval", content: "All conversions and transactions generated by publishers must be reviewed and approved by the Linktrackify admin team. Only approved transactions are eligible for payment." },
    { title: "2. Advertiser Payment Confirmation", content: "After transactions are approved, advertisers must first pay Linktrackify for those transactions. Payments to publishers will only be processed after Linktrackify receives the corresponding payment from the advertiser." },
    { title: "3. Next Payout Allocation", content: "Once advertiser payment is received and confirmed, the transactions will be marked for the next payout cycle. Publishers will be able to see the eligible amount in the Next Payout section on their dashboard and payments page." },
    { title: "4. Payout Schedule", content: "Publisher payouts are processed between the 25th and 30th of each month. Only the amount displayed in the Next Payout section before the payout date will be included in that month's payment." },
    { title: "5. Payment Method", content: "All publisher payments are made via Payoneer to the Payoneer email address provided in the publisher's account settings. Publishers must ensure that their Payoneer email address is correct and active." },
    { title: "6. Incorrect Payment Details", content: "Linktrackify is not responsible for payments sent to incorrect Payoneer email addresses. Publishers are solely responsible for providing accurate payment information." },
    { title: "7. Minimum Payout Threshold", content: "The minimum payout threshold is $50.00. If your balance is below this amount at the time of the payout cycle, it will be carried over to the next cycle." },
  ];

  return (
    <Layout title="Payments" subtitle="View your payment history and manage payment information">
      <div className="space-y-5">
        {/* Tabs */}
        <div className="flex gap-2">
          <button onClick={() => setActiveTab("history")}
            className={`px-5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 ${activeTab === "history" ? "bg-white text-blue-600 shadow-sm border border-blue-100" : "text-gray-500 hover:text-gray-700 hover:bg-white"}`}>
            Payment History
          </button>
          <button onClick={() => setActiveTab("information")}
            className={`px-5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-200 ${activeTab === "information" ? "bg-white text-blue-600 shadow-sm border border-blue-100" : "text-gray-500 hover:text-gray-700 hover:bg-white"}`}>
            Payment Information
          </button>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {stats.map((stat) => (
            <div key={stat.label} className={`bg-white rounded-2xl border ${stat.border} shadow-sm p-5 flex items-center gap-4`}>
              <div className={`w-12 h-12 ${stat.bg} rounded-xl flex items-center justify-center flex-shrink-0 ${stat.color}`}>{stat.icon}</div>
              <div>
                <div className="text-2xl font-bold text-gray-900">{stat.value}</div>
                <div className="text-xs text-gray-500 font-medium">{stat.label}</div>
              </div>
            </div>
          ))}
        </div>

        {activeTab === "history" && (
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
            <div className="p-5 border-b border-gray-100">
              <h3 className="font-bold text-gray-900">Payment History</h3>
            </div>
            <div className="py-16 text-center">
              <svg width="40" height="40" fill="none" viewBox="0 0 24 24" stroke="#d1d5db" strokeWidth={1.5} className="mx-auto mb-3">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
              </svg>
              <p className="text-sm text-gray-400 font-medium">No payment history found</p>
              <p className="text-xs text-gray-300 mt-1">Your payment history will appear here once payments are processed</p>
            </div>
          </div>
        )}

        {activeTab === "information" && (
          <div className="space-y-5">
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
              <div className="flex items-center gap-3 mb-5">
                <div className="w-10 h-10 bg-orange-50 rounded-xl flex items-center justify-center">
                  <svg width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="#f97316" strokeWidth={1.8}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
                  </svg>
                </div>
                <div>
                  <h3 className="font-bold text-gray-900">Payoneer Account</h3>
                  <p className="text-xs text-gray-400">Payments are sent to your Payoneer email each payout cycle</p>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5">Payoneer Email Address <span className="text-red-500">*</span></label>
                <input type="email" value={payoneerEmail} onChange={(e) => setPayoneerEmail(e.target.value)}
                  placeholder="Enter your Payoneer email address"
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all" />
                <p className="text-xs text-gray-400 mt-1.5">This email will be used to send your payments via Payoneer</p>
              </div>
              <div className="mt-5 flex items-center gap-3">
                <button onClick={handleSave}
                  className="bg-blue-600 hover:bg-blue-700 text-white font-semibold px-6 py-2.5 rounded-xl transition-all text-sm">
                  Save Payment Info
                </button>
                {saved && (
                  <span className="text-sm text-emerald-600 font-medium flex items-center gap-1.5">
                    <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>
                    Saved successfully!
                  </span>
                )}
              </div>
            </div>

            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
              <h3 className="font-bold text-gray-900 mb-6">Linktrackify Publisher Payment Terms</h3>
              <div className="space-y-5">
                {paymentTerms.map((term) => (
                  <div key={term.title} className="pb-5 border-b border-gray-50 last:border-0 last:pb-0">
                    <h4 className="text-sm font-bold text-gray-800 mb-1.5">{term.title}</h4>
                    <p className="text-sm text-gray-500 leading-relaxed">{term.content}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}